# 忍耐について

>ならば（使徒よ、彼らの嘲笑と挑発に）、よき忍耐で忍耐せよ。
>
> \- 階段章 70:5

忍耐（サブル）は義務（ワージブ）の礼拝行為の一つです。信仰の半分を占めると言われています。（残りの半分は感謝であると言われています。）

>信仰する者たちよ、忍耐と礼拝をもって助力とせよ。本当にアッラーは、忍耐ある者たちと共におられるのだから。
>
> \- 雌牛章 2:153

ハディースでは忍耐に関してはこう伝えられています：

>アナス（アッラーのご満足あれ）の伝承によると：
>
>ムハンマド（祝福と平安あれ）ﷺは、「真の忍耐とは、まさに（困難の）最初の衝撃の際にあるものである。」と言われました。
>
> \- サヒーフ・ブハーリ 1302

クルアーンでは耐え忍ぶ者についてこう言われています：

>...アッラーは、忍耐ある者たちをお好みになる。
>
> \- イムラーン家章 3:146

>そのような者たち、彼らの上には、その主からの賞賛とご慈悲がある。そしてそのような者たちこそは、正しく導かれた者たちなのである。
>
> \- 雌牛章 2:157

>…そしてわれらは忍耐した者たちに対し、彼らが行っていた最善のもので、必ずやその褒美を報いてやるのだ。
>
> \- 蜜蜂章 16:96

>「…本当に忍耐する者たちは、その褒美を際限なく全うされる」。 
>
> \- 集団章 39:10

次のアヤー（節）では忍耐が正しい信仰の証であることが語られます：

>善とは、ただあなた方の顔を東や西に向けることではない。しかし（真の）善（行者）とは、アッラー、最後の日、天使、啓典、預言者たちを信じ、財産を近親の者、孤児、貧者、旅路（で苦境）にある者、物乞い、首のために、自らの（それに対する）愛着に関わらず施し、礼拝を遵守し、浄財を支払い、約束すればそれを果たす者たちで、困窮と災難、戦いの時に忍耐ある者たち。そのような者たちこそは、（信仰に）正直な者。そしてそのような者たちこそは、敬虔な者なのである。
>
> \- 雌牛章 2:177

審判の日にアッラーは耐え忍ぶ人たちについてこう仰せられます：

>本当にわれはこの日、彼らが（現世で）忍耐していたことゆえに、彼らこそを成功者とすることで、彼らに報いてやるのだ。
>
> \- 信者たち章 23:111

イブン・カイイム・アル=ジャウズィーヤ師によれば、アッラーは忍耐強い人々と共におられ、その結びつきは、信者や不信者を問わず全ての人々に及ぶ一般的な関係を遥かに超越した特別なものであると言われています：

>…忍耐するのだ。本当にアッラーは（そのご援助によって）、忍耐する者たちと共にあるのだから。
>
> \- 戦利品章 8:46

また、イブン・カイイムは次のようにも述べています：

>忍耐は善に満ちており、忍耐以上に優れた贈り物は他にありません。
>
> \- イブン・カイイム・アル=ジャウズィーヤ