# 忍耐の定義

## サブルの意味 {.unnumbered .unlisted}
\
クルアーンやハディースにおいて「忍耐」と訳されることの多いアラビア語は「サブル」です。サブルという言葉は、単に「我慢」や「忍耐」だけを指すものではありません。ムフティー・イスマイル・ビン・ムーサ・メンクとイマーム・アル=ガザーリ師によれば、サブルには「寛容」「忍耐強さ」「不動の心」「持続性」そして「自制」といった意味も含まれています。自制心と持続性を伴う忍耐の例は、クルアーンの第18章「洞窟（アル・カハフ）」の中に見ることができます。

>また（預言者よ）、その御顔を望みつつ、朝に夕に自分たちの主（だけ）に祈る者たちと共に、忍耐せよ。そして現世の生活の飾りを欲して、あなたの眼が彼ら（信仰者たち）から（不信仰者へと）逸れてしまうようではならない。また、われらがその心をわれらの唱念から遠ざけさせ、自らの欲望を追求し、その状態が破滅に陥ってしまった者に従ってはならない。
>
> \- 洞窟章 18:28

## 学者による定義 {.unnumbered .unlisted}
\
多くの学者が、独自の視点から「サブル」を定義しています。その中からいくつかの例をご紹介します：

>サブルとは、魂の勇敢さである。
>
> \- イブン・カイイム・アル＝ジャウズィーヤ師

>忍耐の本質とは、欲望の衝動に直面した際の、信仰による動機づけの堅固さである。
>
> \- イマーム・アル=ガザーリ師

>[忍耐強い人とは] いかなる逆境にも立ち向かえるよう、自らを鍛え上げた人のことである。
>
> \- アブー・ウスマーン・アッ=サーブーニー師

>サブルとは、アッラーと共に不動であり続け、彼（アッラー）からのいかなる試練をも、落ち着きと寛大な心で受け入れることである。
>
> \- アムル・ビン・ウスマーン・アル=マッキー師

>サブルとは、クルアーンとスンナの定めに従い、忍耐し続けることである。
>
> \- イブラーヒーム・アル＝ハッワース師

## 忍耐と不平について {.unnumbered .unlisted}
\
サブルとは、外面的な不平を漏らさずに試練に立ち向かうことである、と主張する学者もいます。

>[サブルとは] 不満を訴えないことである。
>
> \- アブー・ムハンマド・ルワイム・ビン・アフマド師

>サブルとは、不快な表情を一切見せずに、苦渋を飲み込むことである。
>
> \- アル＝ジュナイド・ビン・ムハンマド師

>サブルとは、恩恵にあずかっている時も逆境にある時もそれらに無関心であり、どのような状況下でも心が平穏に保たれていることを意味する。
>
> \- アブー・ムハンマド・アル＝ジャリーリー師

イブン・カイイム師は、苦痛に対して全くの無感覚でいることは人間に不可能であり、また宗教的にも求められていることではないと主張します。私たち人間には、苦痛よりも安寧を好むという天性が備わっているからです。預言者ムハンマド（祝福と平安あれ）でさえ、苦境の際にアッラーに助けを乞いました。その美しい例が、ターイフのドゥア（祈願）に見られます。

>アブドゥッラー・イブン・ジャアファル（アッラーのお悦びあれ）の伝承により、預言者ムハンマド（祝福と平安あれ）が次のようなドゥアを捧げられたことがアット＝タバラーニーによって報告されています。
>
>「アッラーよ、私は、自らの力の弱さ、なす術のなさ、そして人々の前での卑しさを、あなたのみに訴えます。慈悲深き者たちの中でも最も慈悲深きお方。あなたは虐げられた者たちの主であり、私の主であられます。」

苦難について語ることは、サブルと矛盾するものではありません。クルアーンに記された預言者アイユーブ（祝福と平安あれ）の例が、そのことを示しています。彼（祝福と平安あれ）は自らの苦しみを口にし、アッラーに助けを乞われました。その叫びは、以下のように記されています。

>また（使徒よ）、アイユーブ（のことを思い起こさせよ）。彼が、「私に災難が降りかかりました。それでも、あなたは慈しみ深い者の中でも、最も慈しみ深いお方であられます」と（言って）、その主を呼んだ時のこと。
>
> \- 預言者章 21:83

それにもかかわらず、アッラーはアイユーブ（祝福と平安あれ）について、クルアーンの中で次のように仰っています。

>実にわれらは、彼が忍耐する者であることを認めた。僕（アイユーブ）の素晴らしいことよ、本当に彼は常に回帰する者なのだから。
>
> \- サード章 38:44

アッラーに訴えること（忍耐と矛盾しない行為）に対し、アッラーについて不平を漏らすこと（忍耐と矛盾する行為）には注意が必要です。

## サブルの得べき道 {.unnumbered .unlisted}
\
アッラーの助けがあれば忍耐を身につけることは可能です。これはアッラーからの慈悲であり、恵みであります。

>アブー・サイード（アッラーのお悦びあれ）による伝承です。
>
>「忍耐しようと努める者は、アッラーによって忍耐強くさせられます。忍耐よりも良く、また、より広大な恵みを授けられた者は、誰一人としておりません。」
>
> \- ジャーミ・アッ＝ティルミズィー 2024

ムスリムがいかなる状況にあっても、それが「最善の状況」となり得るのは、サブルがあるからこそだということを、私たちは心に留めておくべきです。

>スハィブ（アッラーのお悦びあれ）の伝承によれば、アッラーの使徒（祝福と平安あれ）は次のように仰いました。
>
>信者のありよう（物事の状態）は、驚くべきものです。なぜなら、彼に関わるすべての出来事は、彼にとって最善（ハイル）となるからです。そして、それは信者以外にはあり得ないことです。もし喜ばしいことがあれば、彼は（アッラーに）感謝し、それは彼にとって最善となります。また、もし苦難に見舞われれば、彼は忍耐し、それもまた彼にとって最善となるのです。
>
> \- サヒーフ・ムスリム 2999