#　忍耐の必要性

>時間にかけて（誓う）。本当に人間は、まさしく損失の中にある。信仰し、正しい行いを行い、真理（の固守とアッラーへの服従）を勧め合い、忍耐を勧め合う者たち以外は。
>
> \- 時間章 103:1-3

イスラムにおいて忍耐（サブル）は非常に重要な概念であり、クルアーンの中では「サブル」から派生した言葉が８０以上も登場します。私たちが常に目指すべき美徳の一つとして示されています。

>また忍耐し、赦してやる者こそは、本当にそれこそは、あなた方が決意を固めるべき事柄の内のもの。
>
> \- 協議章 42:43

クルアーンにおいて、預言者や指導者たちは忍耐の美徳を体現する存在として描かれています。私たちは彼らを模範とし、その忍耐強さに倣うよう努めるべきなのです。

>また、われらは彼ら（イスラーイールの子ら）が忍耐した時、彼らの内から、われらの命令によって導く導師たちを出した。そして彼らは、われらの御徴をこそ、確信していたのである。
>
> \- 平伏礼章 32:24

>ならば（使徒よ）、使徒たちの内の決然とした者たち[1]が忍耐したごとく、忍耐せよ。
>
> \- 砂丘章 46:35

## 人生の目的 {.unnumbered .unlisted}
\
私たちに忍耐が必要とされる大きな理由の一つは、この人生そのものが、善い行いができるかどうかを問われる「試練」の場だからです。永遠に生きられる人間はおらず、誰もがいつか「死」という門をくぐることになります。こうした試練の不可避さについて説いたアーヤ（節）が数多く存在します。

>一体人々は、「私たちは信仰した」と言うことで、試練にかけられることもなく、放って置かれるとでも思ったのか？また、われらは確かに、（使徒が遣わされた）彼ら以前の者たちを試練にかけたのだ。それでアッラーは、（信仰に）正直な者たちを必ずやご存知になり給い、嘘つきたちを必ずやご存知になり給う。
>
> \- 蜘蛛章 29:2-3

>また（信仰者たちよ）、われらは必ずや、あなた方を試練にかける。われらが、あなた方の内の努力奮闘する者たちと、忍耐ある者たちを如実に表し、あなた方の消息を試すために。
>
> \- ムハンマド章 47:31

クルアーンでは、その試練の目的も明確に示されます。

>本当にわれらは、地上にあるものを、その飾りと（、地上の住人の利益と）した。（それは）われらが、彼らの誰が最も行いが善いか、試練にかけるため。
>
> \- 洞窟章 18:7

>いや、（教友たちよ、）あなた方は、アッラーがあなた方の内の努力奮闘する者たちを如実に表されず、忍耐ある者たちを露わにされてもいないというのに、天国に入れるとでも思い込んでいたのか？
>
> \- イムラーン家章 3:142

試練の具体的な中身についても、詳しく説かれています。

>われらは、いくばくかの恐怖や飢え、財産や生命や果実の損失によって、必ずやあなた方を試練にかける。忍耐する者たちには、吉報を伝えよ。（彼らは）災難が降りかかれば、「本当に私たちは、アッラーにこそ属します。そして必ずや私たちは、かれの御許へと帰り行くのです」と言う者たち。
>
> \- 雌牛章 2:155

クルアーンは、私たちが忍耐強くあるよう、常に励ましを与えてくれます。

>…もしあなた方が忍耐するなら。それこそは忍耐する者たちにとってより善いことなのだ。
>
> \- 蜜蜂章 16:126

>信仰する者たちよ、（アッラーへの服従において）忍耐し、（敵との）我慢比べに打ち勝ち、前線を守れ。そしてあなた方が成功するべく、アッラーを畏れるのだ。
>
> \- イムラーン家章 3:200

最終的には、私たちが健全な視点を持ち続け、来世はこの現世よりも遥かに長いものであると、常に心に留めておくべきです。

>かれ（アッラー）は、（地獄の民に）仰せられる。「あなた方は地上で、何年間過ごしたのか？」彼らは（応えて）申し上げる。「一日か、一日足らずを、過ごしました。ならば、数える者たちにお尋ねください」。
>
> \- 信者たち章 23:112-113