# 苦難と平穏

人間が直面するすべてのことは、二つのカテゴリーのいずれかに分けられます。自分の欲望に沿うものか、あるいはそれに反するものかです。私たちは、困難な時だけでなく、平穏な時にも忍耐が必要です。

## 苦難時の忍耐 {.unnumbered .unlisted}
\
>アッラーは誰にも、その能力以上のものを負わせられない。
>
> \- 雌牛章 2:286

苦難時の忍耐は、最も容易な忍耐です。なぜなら、避けることが不可能だからです。そのような時こそ、アッラーに頼るように教えられています。

>また、どうして私たちが、アッラーに全てを委ねないことがあろうか？かれは私たちを確かに、（救済への）いくつもの道へとお導きになったというのに。私たちは必ずや、あなた方が私たちを害したことに対して、耐え切るのだ。そして（何かを誰かに）委ねる（信仰）者たちには、アッラーにこそ全てを委ねさせよ」。 
>
> \- イブラヒーム 14:12

>いかなる災難も、アッラーのお許しなしには降りかかることがない。そしてアッラーを信じる者は誰でも、かれ（アッラー）がその心を導いて下さろう。アッラーは、全てのことをご存知のお方。
>
> \- 互いに無視する章 64:11

>サブル（忍耐）とは、アッラーに忠実であり続け、どのような試練も落着きと寛容な心をもって受け入れることです。
>
> \- アムル・ビン・ウスマーン・アル＝マッキー

苦難の時に忍耐強くある人々は、クルアーンの中で「正義の人々」として記されています。

>善とは、ただあなた方の顔を東や西に向けることではない。しかし（真の）善（行者）とは… 困窮と災難、戦いの時に忍耐ある者たち。そのような者たちこそは、（信仰に）正直な者。そしてそのような者たちこそは、敬虔な者なのである。 
>
> \- 雌牛章 2:177

## 平穏時の忍耐 {.unnumbered .unlisted}

>すべての信者は苦難の時に忍耐しますが、平穏な時においてまで忍耐強くあり続けられるのは、真実を貫く者（誠実な者）だけであると言えます。
>
> \- アル＝ガザーリー

学者のイブン・ジュザイ・アル＝カルビーは、平穏時の忍耐を「恵みを責任を持って扱うための自制」であると定義しました。健康、安全、富、そして地位に恵まれていても、自分がどこから来たのか、そして自らの最終的な帰着点を忘れてはなりません。これは非常に難度の高い忍耐です。クルアーンには次のように記されています。

>また（不信仰な）人間は、有害が降りかかれば、横になって、または座りつつ、あるいは立ちながら、われらに祈る。そして、われらが彼からその害悪を取り除いてやれば、彼は自分に降りかかった害悪（からの救い）について、われらに祈りなどしなかったかのように（以前の不信仰な状態を）続ける。
>
> \- ユーヌス章 10:12

サハーバ、預言者ムハンマド（祝福と平安あれ）の最も敬虔な教友たちでさえ、それを困難だと感じました。

>アブドゥッラフマーン・ビン・アウフは次のように述べました。
>
>「私たちはアッラーの使徒ﷺと共に苦難という試練を受け、それを耐え忍びました。しかし彼の後、繁栄という試練を受けたとき、私たちは忍耐することができませんでした。」
>
> \- ジャーミ・アッ＝ティルミズィー 2464ｋ

クルアーンは、私たちが大切にしているものでさえ、時に私たちをアッラーから遠ざける「誘惑」や「慢心」になりかねないことを警告しています。

>信仰する者たちよ、あなた方の財産と子供たちが、あなた方をアッラーの唱念から背けさせてしまうようではならない。誰であろうとそうする者、それらの者たちこそは損失者なのである。 
>
> \- 偽信者たち章 63:9

平穏な時の忍耐とは、人生をアッラーから預かった「アマナー（信託）」として捉えることです。これを自覚することで、私たちは不注意という落とし穴を避け、授かった恵みに感謝することができます。預言者スレイマン（祝福と平安あれ）はその素晴らしい手本です。

>「これは、私が果たして感謝するか、あるいは恩知らずとなるか試みるための、我が主からの恩寵である。感謝する者は、誰でも、感謝することで自分自身を益するに外ならず、恩知らずな者があろうと、本当に我が主は、（そのような者の感謝を必要とはされない）満ち足りたお方、（そのような者にもお恵みになる）貴い*お方であられるのだ」。 
>
> \- 蟻章 27:40

正しい信仰とは、平穏を「人格の試練」として捉えることを求めます。スフヤーン・アッ＝サウリーが総括したように、「我々の信仰において、苦難は恵みであり、安楽こそが忍耐の真の試練であると自覚し、確信して初めて、人は真の信仰心を持ったと言えるのです。」