# 忍耐の美徳

>われらは、いくばくかの恐怖や飢え、財産や生命や果実の損失によって、必ずやあなた方を試練にかける。忍耐する者たちには、吉報を伝えよ。
>
> \- 雌牛章 2:155

クルアーンの中では、忍耐を持つよう繰り返し励まされています。忍耐の美徳についても随所で述べられており、アッラーが忍耐強い者を愛されるということは、クルアーンに直接述べられています。

>アッラーは、忍耐ある者たちをお好みになる。 
>
> \- イムラーン家章 3:146

そして、クルアーンにはアッラーが忍耐強い者と共にいらっしゃることが述べられています。

>アッラーは（そのご援助と共に）、忍耐強い者たちと共におられる。
>
> \- 戦利品章 8:66

これは忍耐における非常に重要な美徳であり、雌牛章(2:153と2:249)や戦利品章(8:46)などでも繰り返し述べられています。

ハムザ・ユスフ師によると、忍耐は心の安らぎ、アッラーの慈悲、そして導きをもたらしてくれます。以下のハディースは、忍耐がどのようにアッラーの許しへと導いてくれるのかを伝えています。

>アブー・サイード・アル＝フドリーとアブー・フレイラ（アッラーのお悦びあれ）の伝承によれば：
>
>預言者（祝福と平安あれ）は, 次のように言われました。
>
>「ムスリムが経験する疲れ、病気、悩み、悲しみ、害悪、苦痛は、たとえ足に刺さった一本の棘であっても、それによってアッラーがその人の罪の一部を消し去ってくださらないものはない。」
>
> \- サヒーハ・アル＝ブハーリー 5641, 5642

忍耐によって大きな報いを得る機会であるため、試練は恵みであると言えます。忍耐に対する報いについては、クルアーンの中に何度も述べられています。

>イスラーイールの子らに対するあなたの主のよき御言葉が、彼らが忍耐したことゆえに完遂されたのだ。
>
> \- 高壁章 7:137

>「本当に忍耐する者たちは、その褒美を際限なく全うされる」。
>
> \- 集団章 39:10

忍耐強い者の報いが失われることはない、ということもまた、明確にされています。

>そして忍耐せよ。本当にアッラーは、善を尽くす者たちの褒美を無駄にはされないのだから。
>
> \- フード章 11:115

>「本当に誰であろうと、（アッラーを）畏れ、忍耐する者、実にアッラーは（そのように）善を尽くす者たちの褒美を無駄にされることがないのです」。
>
> \- ユースフ章 12:90

忍耐強い者への最大の報酬は、アッラーの慈悲による審判の日での成功です。これについては、クルアーンで次のように述べられています。

>それでアッラーは、その日の悪から彼らをお守りになり、彼らに（顔の）輝きと（心の）喜びをお授けになった。そして彼らが（現世で）忍耐したことゆえに、彼らを楽園と絹（の衣服）でお報いになった。彼らはそこで、寝台に寄りかかっている。彼らはそこで、太陽（の灼熱）も酷寒も見出すことがない。
>
> \- 人間章 76:11-13

>「本当にわれはこの日、彼らが（現世で）忍耐していたことゆえに、彼らこそを成功者とすることで、彼らに報いてやるのだ。」
>
> \- 信者たち章 23:111

>そしてそれは、忍耐する者しか手にすることがなく、それは（現世と来世における、）この上ない幸福の持ち主しか手にすることはない。
>
> \- 解説された章 41:35

ジャンナ（天国）は、クルアーンの中で次のように描写されています。

>（それは）彼らと、彼らの祖先、配偶者、子孫の内で正しかった者、が入ることになる、永久の楽園。天使たちも（彼らを祝福すべく）、全ての扉から彼らのもとに入る。（天使たちは、彼らに言う。）「あなた方が（現世で、アッラーへの服従において）忍耐したことゆえ、あなた方に平安を」。そして世の（善き）結末は、何と素晴らしいことか。
>
> \- 雷章 13:23-24