#  義務としての忍耐

## 礼拝の実践における忍耐

  - Patience in Worship: Sabr 'ala ta'at Allah / Sabr 'ala taAla
  - This is difficult on the ego. It means being consistent with prayer and worship. This is one of the highest forms of patience. 
  - This comes in three parts: 1. starting worship with correct intention and sincerity 2. During the deed being focused with good etiquette and presence of heart 3. After worship being patient with the rememberance of Allah and not showing off for the sake of reputation  
  - 2:264 “Cancel not your charity by reminders of your generosity or injury.”
  - Hadith: “Fasting is half of faith.” (Patience as a reaction to desire's call)
  - Surah Maryam: "Indeed He is the Lord of the skies and the earth, and whatever is between the two, so worship Him and endure and persevere..."
  - Ta-Ha: "Command your family to fulfill the salah and be patient."
  - "And command your family to pray, and be steadfast in patience over it."
  - Ar-Rad: "those who bear sabr for the sake of Allah and establish salah and spend from what Allah has given them publicly and privately..."
  - The example of patience during teraweeh. 

## 禁止行為を避ける上での忍耐

 - Patience in refraining from what is harmful and forbidden: Sabr 'an ma'asi Allah
 -  "Sabr is to remain patient on the rulings of the Quran and the sunnah." - Al-Khawwas 
 -  "Remembering Allah and restraining onself from sin is sabr." Mufti Menk 
 -  This is a difficult type of patience, especially for acts which have become a habit, as two forces (desire and habit) are at odds with religious motivation. 
 -  Sins of the tongue are one example of this. They are easy to do, and much patince is required in refraining from such sins. 
 -  Hadith "The fighter is he who fights is desire, and the emigrant is he who emigrates from evil."
 -  "The battlefield is the heart of man." - Ibn Qayyim 
 -  We are constantly battling our inner desires, which requires patience (which is an opposing force, "restraint"). 
  -  "Steadfastness is the control of the rule of intelligence and religion against the desire to fulfill one's lust and passion." - Unknown 
     - “Good acts are carried out both by the good and bad doer, but only the patient can leave sins. Ibn Taymiyyah.
     - Hadith: "If man didn't sin I would replace them with a creation that sins and turns to Me in repentance." 

## 苦難時の忍耐

This is called Sabr 'ala al-Qadr Allah. Belief in the Qadr of Allah is a pillar of faith in Islam and is required of believers. Something positive? Alhamdullilah. Something negative? Alhamdullilah - this is an opportunity to gain closeness to Allah. The vast majority of calamities are caused by sins, whether individual or collective, and some are simply trials. 
"Allay says "I know what you do not know."" (angels make dua) 
 It comes in two parts: 

### (Complete lack of Control) {.unnumbered .unlisted}

   - “If Allah opens the doors of contemplation in their heart they become grateful.” Ibn Taymiyyah
      - "We believe that good a nd bad fate comes from the Almighty." Mufti Menk
      - Examples: Death of a loved one, loss of wealth or health, and other types of tribulation. 
      - "Having patience with these is from the loftiest stations." Al Ghazali 
      - “My Lord! Help me to remember You, to thank You, and to worship You well.” Prophetic dua 
      - Hadith: The Prophet (pbuh) said "Allah said, "If I try my slave with a tribulation of sickness and he is patient and does not complain to his visitors, I will replace his flesh with a flesh  better than it, and his blood with blood better than it..."
      - Quran: "Give good tidings to the patient, who when calamity comes they say inna lillahi wa inna ..."
      - Hadith: He (pbuh) said, informing us from Allah, "If I direct to a slave among my slaves an affliction in his body, wealth, or children, and he faces it with beautiful patience, on the Day of Resurrection I will be Shy about placing his deeds or opening his record."
      - Hadith: He (pbuh) also said that "Among the affairs that entail magnifying Allah and knowing His Right is that you do not complain about your pain and do not mention your affliction."
      - 2:155-157 “Give good tidings to those who are steadfast, and those who say, when afflicted with calamity…”
      - Musa (as)'s dua "la hawla wa la quwatta illah billah"
      - Prophet Yaqub (as) only taking his sorrow to Allah.  
      - "...and rely upon Allah. And Sufficient is Allah as Disposer of affairs." Al-Ahzab (the Allies) 33:48


### (Some else did Harm) {.unnumbered .unlisted}

   - Hadith: Upon being harmed he ﷺ would say “May Allah have mercy upon Musa!”
     - Al-Imran "When goodness comes to you it hurts them..."
     - Al-Imran "You will be tested by your wealth... and you will hear harm from those given the book in the past and they will laugh at you. If you are patient it is best for you." 
     - This type of patience is difficult to bear because of the desire for revenge. 
     - This is the kind of patients the Prophets ﷺ had, and it is said about them: 32:24 “And we make from among them leaders guiding by Our command when they were patient…”
     - "...And we will surely be patient against whatever harm you should cause us. And upon Allah let those rely who would [indeed] rely." Ibrahim 14:12
     - And We already know that your breast is constrained by what they say. So exalt [Allah] with priase of your Lord and be of those who prostrate [to Him]." Al-Hijr (the Rock) 15:97-98
     - Hadith: Some of the companions (ra) said: "We did  not consider a man's faith to be true unless he was patient when harmed." 
     - This kind of patience can make an enemy a friend, as described in 41:34-35 “Upon the one thereupon you is emnity… repel evil with good”
     - Hadith from Ibn Taymiyyah Chapter 5
     - “And if you are patient and fear Allah, their plot will not harm you at all. Indeed, Allah is encompassing of what they do.” 3:120
     - 11:11 “Except those who are steadfast and do good deeds…”
     - 42:43 “The one who is steadfast and forgives that is one of the greatest things.”