# 忍耐の段階

• 最高位：欲望を完全に抑え込む
• 中間：葛藤と混在
• 最下位：宗教的動機が欲望に負ける


 - 3:200 “…Vie in steadfastness, strengthen each other…”
 - Ibn Taymiyyah chapter 9 page 25 quote “whoever is sincere in seeking something, the patience observed in seeking it is is recompensed in accordance to his sincerity” 
 - Highest: A person subdues desire's call entirely. 
   - 46:13-14 "... there will be no fear concerning them..."
   - 89:27-29 "...return to your Lord, pleased and well-pleasing..."
   - “Fortunate are those who attain the best way for their life through their steadfastness, advance to the highest ranks and enter the garden of bliss on the wings of their patience and gratitude” Ibn Qayyim (Page 8)
 - Lowest: Desire's call is strong, religious motivation declines, and desire overcomes. 
   - 32:13 "... I will surely fill Hell with jinn and people."
   - 25:44 "...They are not except like livestock..."
   - This has two signs. 1: "I want to repent, but it is difficult for me, so I have no aspiration to do so." 2: "Allah is Mericful, Generous, and does not need my repentance - the expanse of Paradise will not be tightened for me, nor will His all-encompassing Forgiveness."
- Intermediate: Those who struggle, having ups and downs, and whose deeds are mixed. They mix righteous actions with those that are bad. They abandon some desires, but are unable to refrain from what is stronger. At all times they are remorseful.
- Mufti Menk: It is like a baby learning to walk who falls many times while growing. We strive with imperfect patience and make mistake as we grow. 
   - "So long as a person is mindful of Allah and believes in the good of tuhe afterlife, then Allah will facilitate ease for them." - Al Ghazali 