# 参考資料　{.unnumbered .unlisted}

## クルアーンとハディース {.unnumbered .unlisted}

聖クルアーン：日亜対訳注解　訳：サイード佐藤

クルアーン　やさしい和訳　監訳著：水谷周　訳補完：杉本恭一郎

４０のハディース　編：イマーム･アンナワウィー　訳：黒田壽郞

## クルアーン解釈（タフスィール）{.unnumbered .unlisted}

Tafsir Ibn Kathir – Isma’il ibn Kathir

Ma’arif Al-Quran – Mufti Muhammad Shafi

Tafsir al-Jalalayn – Al-Mahalli & Al-Suyuti

Tafsir Ibn Ashur

Asab al-Nuzul – Al-Wahidi

Tafsir Tazkirul Quran

Tafheem-ul-Quran – A. Maududi

## イスラーム古典典籍 {.unnumbered .unlisted}

The Forty Principles of the Religion – Imam Al-Ghazali

The Principle of Patience – Sheikh al-Islam Ibn Taymiyyah

Patience and Gratitude – Ibn Qayyim al-Jawziyyah

Trials and Tribulations – Ibn Qayyim al-Jawziyyah

## 現代の著作 {.unnumbered .unlisted}

The Sealed Nectar – Safiur-Rahman Al-Mubarakpuri

Don’t Be Sad (La Tahzan) – ‘Aidh ibn Abdullah al-Qarni

Purification of the Heart – Sheikh Hamza Yusuf

After Beautiful Patience – Elias Malik

Journey Through the Quran – Sharif H. Banna

## イスラーム講義 {.unnumbered .unlisted}

シェイク・アルマンスール・アフマド師による講義

シェイク・前野（アハマド）直樹師による講義

ムフティ・イスマイル・メンク師による講義

シェイク・ハムザ・ユスフ師による講義

シェイク・ベラル・アッサド師による講義

ドクター・ハイファ・ユニス師による講義